.github: check for modified bytecode (#47)
Adding a build step that checks if any committed bytecode files are
changed after running make build. This is supposed to ensure people
can't submit changes without committing up-to-date bytecode.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,6 +27,14 @@ jobs:
           make build
         id: build
 
+      - name: Ensure committed bytecode files are up-to-date
+        run: |
+          if ! git diff --exit-code -- bytecode; then
+              echo "::error::bytecode files modified during the build. Run 'make build' locally and commit the result."
+              git status
+              exit 1
+          fi
+
       - name: Run Forge build
         # this is mostly here so that warnings from building forge-std
         # do not appear in the test output
